### ISSUE TITLE
Warning: FastBinaryTree not available - how to fix?

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/PHEnix#25]
How do i resolve these missing requirements? 

I have all the stuff `readthedocs` suggests.

```
phenix.py
Warning: FastBinaryTree not available, using Python version BinaryTree.
Warning: FastAVLTree not available, using Python version AVLTree.
Warning: FastRBTree not available, using Python version RBTree.
usage: phenix.py [-h] [--debug] [--version]
                 {run_snp_pipeline,filter_vcf,prepare_reference,vcf2fasta} ...
phenix.py: error: too few arguments
```

**Comment by alexjironkin** [comment]
Those are only installed by bintrees if Cython is also installed. I would also suggest installing Cython then reinstalling pyvcf, as there are faster parsers there, again that are only installed if Cython is present.

We haven't made Cython a requirement, mainly because there is no C code in our package, so it would seem wrong, philosophically, to make Cython a requirement.

**Comment by antunderwood** [comment]
Perhaps we could make a note of this in the docs as Cython being recommended rather than a dependency.

**Comment by tseemann** [comment]
I still haven't figured out how Cython fits into the confusing python universe.
Yours sincerely, old Perl dog.

**Comment by flashton2003** [comment]
also, if you had pyvcf installed before cython, then you need to reinstall bintrees via `pip uninstall bintrees` and then `pip install bintrees`.

**Comment by alexjironkin** [comment]
Yeah, if this worked you shouldn't get the warnings.

You may be able to do this with

`pip install bintrees --upgrade`
